spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/MjuEcs
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jwt:
    secret: d2on37hrhod273mdh24o8mohd2438m4jx
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
server:
  servlet:
    session:
      timeout: 30m